export const screens = {
  NEWUSER: 'NEWUSER',
  USER: 'USER',
  ADD_QUESTION: 'ADD_QUESTION',
  QUESTION: 'QUESTION',
  QUESTION_LIST: 'QUESTION_LIST',
  PREDICTION_LIST: 'PREDICTION_LIST',
  LANDING_PAGE: 'LANDING_PAGE',
  ABOUT: 'ABOUT',
  CONTACT: 'CONTACT',
};

export const screenActions = {
  SWITCH_TO: 'SWITCH_TO',
};

export const marketActions = {
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_PREDICTION: 'ADD_PREDICTION',
};

export const userActions = {
  SELECT_CHOICE: 'SELECT_CHOICE',
}