export const screens = {
  NEWUSER: 'NEWUSER',
  USER: 'USER',
  QUESTION: 'QUESTION',
  QUESTIONS_LIST: 'QUESTIONS_LIST',
  PREDICTION: 'PREDICTION',
  PREDICTIONS_LIST: 'PREDICTIONS_LIST',
};

export const screenActions = {
  SWITCH_TO: 'SWITCH_TO',
};

export const marketActions = {
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_PREDICTION: 'ADD_PREDICTION',
};
