export const screens = {
  NEWUSER: 'NEWUSER',
  USER: 'USER',
  ADD_QUESTION: 'ADD_QUESTION',
  QUESTION_LIST: 'QUESTION_LIST',
  PREDICTION: 'PREDICTION',
  PREDICTION_LIST: 'PREDICTION_LIST',
};

export const screenActions = {
  SWITCH_TO: 'SWITCH_TO',
};

export const marketActions = {
  ADD_QUESTION: 'ADD_QUESTION',
  ADD_PREDICTION: 'ADD_PREDICTION',
};
